name: fin_data_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - requests
  - tqdm
  - jupyter
  - scikit-learn
  - matplotlib
  - seaborn
  - nltk
  - spacy
  - pip
  - pip:
      - yfinance
      - beautifulsoup4
